import keyMirror from 'key-mirror'

export default keyMirror({
    // ListView row Type
    NATIVE_BASE_LIST_SECTION_HEADER: null,
    NATIVE_BASE_LIST_SECTION_ROWS: null,
    NATIVE_BASE_LIST_SECTION_EMPTY: null,

    // Login Menus
    MENU_LOGIN_MAIN_SCREEN: null,

    // Home menu items
    MENU_SECTIONS_MORE: null,
    MENU_SECTIONS_RESTAURANTS: null,
    MENU_SECTIONS_EVENTS: null,
    MENU_SECTIONS_PEOPLE_IN_EVENTS: null,
    MENU_SECTIONS_ORDERED_RECIPES: null,
    MENU_SECTIONS_DETAILED_RECIPE: null,
    MENU_SECTIONS_REVIEWS: null,

    // Home More Menus
    MENU_ITEM_ADD_OR_EDIT_RESTAURANT: null,
    MENU_ITEM_ADD_OR_EDIT_EVENT: null,
    MENU_ITEM_ADD_OR_EDIT_RECIPE: null,
    MENU_ITEM_ADD_OR_EDIT_USER: null,
    MENU_ITEM_ADD_OR_EDIT_REVIEW: null,
    MENU_ITEM_SEARCH_RESTAURANTS: null,
    MENU_ITEM_MANAGE_FRIENDS: null,
    MENU_ITEM_READ_REVIEWS: null,


    // Home Tabs Menus
    MENU_HOME_TABS_HOME: null,
    MENU_HOME_TABS_USER_INFO: null,


    // Detailed Model Menus
    MENU_DETAILED_RESTAURANT_PAGE: null,
    MENU_DETAILED_EVENT_PAGE: null,
    MENU_DETAILED_ORDERED_USER_PAGE: null,
    MENU_DETAILED_RECIPE_PAGE: null,
    MENU_DETAILED_REVIEW_PAGE: null,


    // Photos Browser
    MENU_PHOTO_BROWSER_PAGE: null,
    MENU_TAKE_PHOTO_PAGE: null,

    // Header Left Item Type
    PARALLAX_HEADER_LEFT_ITEM_NONE: null,
    PARALLAX_HEADER_LEFT_ITEM_BACK: null,

    // Parallax View Type
    PARALLAX_BACKGROUND_STATIC_IMAGE: null,
    PARALLAX_BACKGROUND_DYNAMIC_IMAGE: null,

    //Alert Type
    ALERT_TYPE_ERROR: null,
    ALERT_TYPE_SUCCESS: null,
    ALERT_TYPE_ALERT: null,

    // Take photos
    TAKEN_PHOTOS_LIST_RESET: null,
    TAKEN_PHOTOS_LIST_ADD: null,
    TAKEN_PHOTOS_LIST_SAVED: null,

    // Query by different types
    FILTER_BY_OBJECT_ID: null,
    FILTER_BY_UNIQUE_ID: null,

    // Edit Model
    EDIT_MODEL_TOGGLE_TYPE: null,
    ON_EDIT_MODEL_FORM_FIELD_CHANGE: null,
    SAVE_MODEL_REQUEST: null,
    WRITE_MODEL_REQUEST: null,
    WRITE_MODEL_SUCCESS: null,
    WRITE_MODEL_FAILURE: null,
    WRITE_MODEL_DONE: null,


    // Model Form Mode
    MODEL_FORM_TYPE_NEW: null,
    MODEL_FORM_TYPE_EDIT: null,


    // Rating Star List Header View
    HEADER_SVG_BUTTON_TAKE_PHOTO: null,
    HEADER_SVG_BUTTON_EDIT: null,
    HEADER_SVG_BUTTON_WRITE_REVIEW: null,
    HEADER_SVG_BUTTON_ADD_EVENT_FOR_RESTAURANT: null,
    HEADER_SVG_BUTTON_ADD_USER_FOR_EVENT: null,

    // Photos Browser
    PHOTO_BROWSER_OPEN: null,
    PHOTO_BROWSER_CLOSE: null,
    SECTION_PHOTOS_BROWSER_FOR_RESTAURANT: null,
    SECTION_PHOTOS_BROWSER_FOR_EVENT: null,
    SECTION_PHOTOS_BROWSER_FOR_RECIPE: null,
    SECTION_PHOTOS_BROWSER_FOR_USER: null,

    // Query Realm Objects List
    QUERY_PHOTOS_BY_TYPE: null,
    QUERY_NEAR_RESTAURANTS: null,
    SEARCH_NEAR_RESTAURANTS: null,
    QUERY_EVENTS_FOR_RESTAURANT: null,
    QUERY_USERS_FOR_EVENT: null,
    QUERY_RECIPES_FOR_USER: null,
    QUERY_SEARCH_USERS: null,
    QUERY_REVIEWS: null,

    // Parse local Images folders
    PARSE_ORIGINAL_IMAGES: null,
    PARSE_THUMBNAIL_IMAGES: null,


    // Parse Object
    PARSE_CONFIGURE: null,
    PARSE_RECORDS: null,
    PARSE_RESTAURANTS: null,
    PARSE_EVENTS: null,
    PARSE_PEOPLE_IN_EVENTS: null,
    PARSE_USERS: null,
    PARSE_PHOTOS: null,
    PARSE_RECIPES: null,
    PARSE_REVIEWS: null,

    // Login UI
    LOGIN_FORM_TYPE_MAIN: null,
    LOGIN_FORM_TYPE_LOGIN: null,
    LOGIN_FORM_TYPE_REGISTER: null,

    LOGIN_FORM_TYPE_RESET_PASSWD: null,


    // UserProfile Event Type
    USERPROFILE_RESET: null,
    USERPROFILE_LOADED: null,

    // Voting button types
    VOTE_BUTTON_LIST_UPVOTE: null,
    VOTE_BUTTON_LIST_DOWNVOTE: null,
    VOTE_BUTTON_ARTICLE_UPVOTE: null,
    VOTE_BUTTON_ARTICLE_DOWNVOTE: null,
    VOTE_BUTTON_RELATED_UPVOTE: null,
    VOTE_BUTTON_RELATED_DOWNVOTE: null,


    // Voting
    POSTS_UPVOTE: null,
    POSTS_DOWNVOTE: null,
    POSTS_UPVOTE_CACEL: null,
    POSTS_DOWNVOTE_CACEL: null,

    POSTS_VOTING_DONE: null,

    // Users
    LOGGED_IN: null,
    LOGGED_OUT: null,
    SKIPPED_LOGIN: null,
    SET_SHARING: null,
    RESET_NUXES: null,

    // async tasks
    SYNC_TASKS_BEGIN: null,
    SYNC_TASKS_END: null,

    // Folders
    LOADED_USER_FOLDERS: null,
    SELECTED_USER_FOLDER: null,
    ADDED_NEW_FOLDER_WITH_POST: null,

    // AppOverlay
    OVERLAY_MODEL_PUSH: null,
    OVERLAY_MODEL_DISMISS: null,

    // For dashboard
    DASHBOARD_EDIT_ALL_ROWS: null,
    DASHBOARD_EDIT_SINGLE_ROW: null,
    DASHBOARD_EDIT_SINGLE_ROW_CANCEL: null,

    TOGGLE_TABLE_ROW_CHECKBOX: null,
    TOGGLE_TABLE_ROW_ALL_CHECKBOXS: null,

    DASHBOARD_LOADED_PAGINATION: null,
    DASHBOARD_LOADED_TOPICS: null,
    DASHBOARD_RESET: null,

    // PostHome, PostDaily
    LIST_VIEW_LOADED_POSTS: null,
    LIST_VIEW_RESET_ALL_POSTS: null,

    // Detailed Posts
    OVERLAY_DETAILS_POSTS_DISMISS: null,
    OVERLAY_DETAILS_POSTS_PUSH: null,
    OVERLAY_DETAILS_POSTS_POP: null,
    OVERLAY_DETAILS_POSTS_EMPTY: null,
    OVERLAY_DETAILS_POSTS_BACKWARD: null,
    OVERLAY_DETAILS_POSTS_FORWARD: null,

    OVERLAY_LOADED_POSTS_PAGE: null,
    OVERLAY_LOADED_RELATED_POSTS: null,

    SET_PLATFORM: null,
    SET_VERSION: null,

    LOGIN_VIA_SOCIAL: null,

    ON_LOGIN_STATE_CHANGE: null,
    LOGOUT: null,

    ON_AUTH_FORM_FIELD_CHANGE: null,
    SIGNUP_REQUEST: null,
    SIGNUP_SUCCESS: null,
    SIGNUP_FAILURE: null,

    LOGIN_REQUEST: null,
    LOGIN_SUCCESS: null,
    LOGIN_FAILURE: null,

    LOGOUT_REQUEST: null,
    LOGOUT_SUCCESS: null,
    LOGOUT_FAILURE: null,

    SET_SESSION_TOKEN: null,

    RESET_PASSWORD_REQUEST: null,
    RESET_PASSWORD_SUCCESS: null,
    RESET_PASSWORD_FAILURE: null,

    GET_PROFILE_REQUEST: null,
    GET_PROFILE_SUCCESS: null,
    GET_PROFILE_FAILURE: null,

    ON_PROFILE_FORM_FIELD_CHANGE: null,

    PROFILE_UPDATE_REQUEST: null,
    PROFILE_UPDATE_SUCCESS: null,
    PROFILE_UPDATE_FAILURE: null,

    SET_STATE: null,
    GET_STATE: null,
    SET_STORE: null,

    FORGOT_PASSWORD: null,
    LOGIN: null,
    REGISTER: null,

    ON_SHIPMENT_FORM_FIELD_CHANGE: null,
    NEW_SHIPMENT: null,
    NEW_SHIPMENT_REQUEST: null,
    NEW_SHIPMENT_SUCCESS: null,
    NEW_SHIPMENT_FAILURE: null,

    GET_SHIPMENTS_REQUEST: null,
    GET_SHIPMENTS_SUCCESS: null,
    GET_SHIPMENTS_FAILURE: null,

    ON_SHIPMENT_SAVED: null

})
